name: Download Workflow Logs

on:
  workflow_run:
    workflows: ['*']  # Triggers on completion of any workflow
    types:
      - completed

jobs:
  download-logs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      - name: Download workflow logs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Install GitHub CLI if not present
          if ! command -v gh &> /dev/null; then
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh
          fi
          
          # Create logs directory if it doesn't exist
          mkdir -p actions-logs/logs_${{ github.event.workflow_run.id }}
          
          # Download logs using GitHub CLI
          gh run download ${{ github.event.workflow_run.id }} -D actions-logs/logs_${{ github.event.workflow_run.id }}
          
          # If there are any failures, also download the logs specifically
          if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
            gh run view ${{ github.event.workflow_run.id }} --log > actions-logs/logs_${{ github.event.workflow_run.id }}/workflow_log.txt
          fi
          
      - name: Commit and push logs
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add actions-logs/
          git commit -m "chore: add workflow logs for run ${{ github.event.workflow_run.id }}" || echo "No changes to commit"
          git push
