# Content from shared/workflows/security-scan.yml
name: Security Scan

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install PowerShell and Dependencies
        run: |
          # Install PowerShell
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell
          
          # Install PSScriptAnalyzer
          pwsh -Command 'Install-Module -Name PSScriptAnalyzer -Force'

      - name: Run PowerShell Security Scan
        shell: pwsh
        run: |
          $results = Invoke-ScriptAnalyzer -Path ./log-master -Recurse
          $results | ConvertTo-Json | Out-File ps-security-results.json
          if ($results.Severity -contains 'Error' -or $results.Severity -contains 'Warning') {
            Write-Error "PSScriptAnalyzer found issues. Check ps-security-results.json for details."
            exit 1
          }

      - name: Install Snyk
        run: |
          sudo npm install -g snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Node.js Security Scan
        run: |
          cd web-fs-manager
          npm ci
          snyk test --all-projects
