# Content from shared/workflows/security-scan.yml
name: Security Scan

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

jobs:
  security-scan:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            shell: bash
          - os: windows-latest
            shell: pwsh
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up PowerShell Core
        uses: microsoft/powershell@v1
        with:
          powershell-version: '7.3'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run PowerShell Security Scan
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force
          $results = Invoke-ScriptAnalyzer -Path ./log-master -Recurse
          $results | ConvertTo-Json | Out-File ps-security-results.json
          if ($results.Severity -contains 'Error' -or $results.Severity -contains 'Warning') {
            Write-Error "PSScriptAnalyzer found issues. Check ps-security-results.json for details."
            exit 1
          }

      - name: Run Node.js Security Scan
        uses: snyk/actions/node@master
        with:
          args: --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run SAST Scan
        uses: github/codeql-action/analyze@v2
        with:
          languages: javascript, powershell

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'GT-Tooling'
          path: '.'
          format: 'SARIF'
          args: >
            --enableExperimental
            --failOnCVSS 7
            --log "${{ runner.temp }}/dependency-check.log"

      - name: Upload Security Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: |
            ${{ runner.temp }}/dependency-check-report.sarif

      - name: Archive Security Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security-reports-${{ matrix.os }}
          path: |
            ${{ runner.temp }}/dependency-check-report.sarif
            ${{ runner.temp }}/dependency-check.log
            ps-security-results.json
