name: Test Secrets Configuration

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of test to run'
        required: true
        type: choice
        options:
          - all
          - workflow
          - snyk

jobs:
  test-workflow-token:
    if: github.event.inputs.test_type == 'all' || github.event.inputs.test_type == 'workflow'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Test Repository Access
        run: |
          echo "Testing repository access..."
          git config --global user.email "test@example.com"
          git config --global user.name "Test Workflow"
          echo "# Test" >> test.md
          git add test.md
          git commit -m "test: verify workflow token"
          git push origin HEAD:test-workflow-token
          git push origin --delete test-workflow-token

      - name: Test PR Creation
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          commit-message: "test: verify PR creation"
          title: "Test: Verify Workflow Token"
          body: "This is a test PR to verify the WORKFLOW_TOKEN configuration."
          branch: "test/workflow-token"
          delete-branch: true

  test-snyk:
    if: github.event.inputs.test_type == 'all' || github.event.inputs.test_type == 'snyk'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Test Snyk Token
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --test-only

  cleanup:
    needs: [test-workflow-token, test-snyk]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Report Status
        run: |
          echo "Tests completed. Check each job for detailed results."
          echo "If any tests failed, verify the corresponding secret configuration."
