# Content from shared/workflows/version-bump.yml
name: Version Bump

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      submodule:
        description: 'Specific submodule (optional)'
        required: false
        type: string

jobs:
  bump-version:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Set up PowerShell Core
        uses: actions/setup-powershell@v1
        with:
          powershell-version: '7.0'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Bump Version
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $params = @{
            VersionType = "${{ github.event.inputs.version_type }}"
          }
          if ("${{ github.event.inputs.submodule }}") {
            $params.Add("Submodule", "${{ github.event.inputs.submodule }}")
          }
          $scriptPath = Join-Path $pwd "shared/scripts/bump-version.ps1"
          if ($IsWindows) {
            $scriptPath = $scriptPath.Replace('/', '\')
          }
          & $scriptPath @params

      - name: Create Pull Request
        if: matrix.os == 'ubuntu-latest' # Only create PR once
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          commit-message: "chore: bump version ${{ github.event.inputs.version_type }}"
          title: "Version Bump: ${{ github.event.inputs.version_type }}"
          body: |
            Automated version bump via GitHub Actions
            - Type: ${{ github.event.inputs.version_type }}
            - Submodule: ${{ github.event.inputs.submodule || 'all' }}
            
            Tested on:
            - Windows
            - Linux
            - macOS
          branch: "version-bump/${{ github.event.inputs.version_type }}"
          base: ${{ github.event.repository.default_branch }}
